### ISSUE TITLE
No README 

### ISSUE THREAD

**Issue by veredrec** [FACN3/al-profile#16]
This is important... :disappointed:

**Comment by Amirk390** [comment]
Adding those images to the read me 

![photo 19-12-2017 10 46 24](https://user-images.githubusercontent.com/24490876/34249926-06de8db0-e644-11e7-9cc6-029ea2f31fbc.jpg)

![photo 19-12-2017 10 46 56](https://user-images.githubusercontent.com/24490876/34250038-561781c0-e644-11e7-9837-fefb03b4cd15.jpg)

**Comment by Amirk390** [comment]
Hii @veredrec 
how are you @veredrec 
Im glad to hear your great @veredrec 
Issue got fixed @veredrec :smile:

**Comment by veredrec** [comment]
Nice @Amirk390
